### ISSUE TITLE
Unable to sync with PouchDB

### ISSUE THREAD

**Issue by martinkronstad** [ermouth/covercouch#3]
Looks like something is wrong with my implementation, or there is a bug in router.js

When I try to get changes with this command: 
curl -X GET http://bruker1:test@localhost:8000/iks/_changes?timeout=25000&style=all_docs&since=0&limit=100

I get no documents.

If I change the trimPipe to 300 and modify the dseq regex, I can get some results via CURL, but as soon as I try syncing with PouchDB I get a lot of errors, an no documents synced.

Data from the log:
martin@dell:~/prosjekter/covercouch$ node covercouch.js 
2017-04-19T16:33:42.007Z[worker#1][info]: "Cached 3 users"
2017-04-19T16:33:42.048Z[worker#1][info]: "Found _design/acl for iks"
2017-04-19T16:33:42.054Z[worker#1][info]: "Cached DB iks. 1 design docs, 2 ACL docs read."
2017-04-19T16:33:42.055Z[worker#1][info]: "2 DBs precached"
2017-04-19T16:33:42.057Z[worker#1][info]: "CoverCouch start"
ID _design/acl
DSEQ 1
{"seq":"1-g1AAAAGPeJzLYWBg4MhgTmEQTM4vTc5ISXLIyU9O
FIN HERE
ID db6bdff6adcf981cad9082827d0054f9
DSEQ 2
{"seq":"2-g1AAAAGPeJzLYWBg4MhgTmEQTM4vTc5ISXLIyU9O
FIN HERE
body-parser deprecated bodyParser: use individual json/urlencoded middlewares cvr/router.js:151:21
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: write after end
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:439:15)
    at Request.write (/home/martin/prosjekter/covercouch/node_modules/request/request.js:1514:27)
    at end (/home/martin/prosjekter/covercouch/node_modules/request/request.js:552:18)
    at Immediate.<anonymous> (/home/martin/prosjekter/covercouch/node_modules/request/request.js:581:7)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
2017-04-19T16:33:52.192Z[worker#2][info]: "Cached 3 users"
2017-04-19T16:33:52.234Z[worker#2][info]: "Found _design/acl for iks"
2017-04-19T16:33:52.240Z[worker#2][info]: "Cached DB iks. 1 design docs, 2 ACL docs read."
2017-04-19T16:33:52.241Z[worker#2][info]: "2 DBs precached"
2017-04-19T16:33:52.243Z[worker#2][info]: "CoverCouch start"

Changes I made to router.js:
                            id = (data.to(trimPipe).match(/^(data:)?\{[^\{]*"id":"(.+?)","/) || []).last();
                            console.log('ID',id);
                            if (id) {
                                dseq = (data.to(50).match(/^(data:)?\{[^\{]*"seq":"(\d+)\-/) || []).last();

**Comment by ermouth** [comment]
Covercouch is nearly abandoned, so it may not be compatible with latest versions of both dependencies and Pouch/CouchDB. So if you seriously going to use the Covercouch ACL approach (that is in vast majority of cases is an overkill), start with updating libs and fixing incompatibilities.

In your particular case seems that body-parser call needs another format of params.

Please also note, that Covercouch have serious bugs and vulnerabilities in both _list and reduce implementations, so if you plan to use em, they probably need full redesign.

**Comment by martinkronstad** [comment]
Do you know of any good alternatives?

I just need ACL for couchdb , and I want users to be able to share content
with other users ...

Med vennlig hilsen
Martin Kronstad
Mobil: 951 70 230

**Comment by ermouth** [comment]
> Do you know of any good alternatives?

I would be happy to help, but as for time I‘ve written Covercouch, there were no decent streaming implementations, covering entire Couch API. And I now understand why: the approach is too generic, in most cases compact task-specific API is less demanding and much more robust.
